---
title: "3 September 2022 jointprob meeting"
output: html_notebook
editor_options: 
  markdown: 
    wrap: 72
---

# Grid Approximations

A. Five-step protocol in one dimension.

1.  Define a grid

```{r}
p_grid <-seq(from=0,to=1,length.out=100)
```

2.  Define the prior

```{r}
prior <-rep(1,100)/sum(rep(1,100))
sum(prior)
```

3.  Compute the likelihood at each value in grid

```{r}
likelihood <-dbinom(6,size=9,prob=p_grid)
sum(likelihood)
```

4.  Compute product of likelihood and prior

```{r}
unstd.posterior <-likelihood*prior
```

5.  Standardize the posterior, so it sums to 1.

```{r}
posterior <-unstd.posterior/sum(unstd.posterior)
sum(posterior)
```

```{r}
plot( p_grid, posterior, 
      type="b",
      xlab="probability ofwater",
      ylab="posteriorprobability")
mtext( "100 points")
```
```{r}
p_grid <-seq(from=0,to=1,length.out=100)
prior <-rep(1,100)/sum(rep(1,100))
sum(prior)
likelihood <-dbinom(6,size=9,prob=p_grid)
sum(likelihood)
unstd.posterior <-likelihood*prior
posterior <-unstd.posterior/sum(unstd.posterior)
sum(posterior)
plot( p_grid, posterior, 
      type="b",
      xlab="probability ofwater",
      ylab="posteriorprobability")
mtext( "100 points")
```

## Repeat with Step prior

```{r}
sprior <- ifelse(p_grid < 0.5, 0, 1)/sum(ifelse(p_grid < 0.5, 0, 1))
sum(sprior)
likelihood <-dbinom(6,size=9,prob=p_grid)
unstd.sposterior <-likelihood*sprior
sposterior <-unstd.sposterior/sum(unstd.sposterior)
sum(sposterior)

plot( p_grid, sposterior, 
      type="b",
      xlab="probability of water",
      ylab="posterior probability")
points(p_grid, sprior, col='magenta')
points(p_grid, posterior, col='cyan')
mtext( "Step prior, 100 grid points")
```

## Repeat with Peaked prior

```{r}
pkprior <- exp( -5*abs(p_grid -0.5))/sum(exp( -5*abs(p_grid -0.5)))
sum(pkprior)
pklikelihood <-dbinom(6,size=9,prob=p_grid)
unstd.pkposterior <-pklikelihood*pkprior
pkposterior <-unstd.pkposterior/sum(unstd.pkposterior)
sum(pkposterior)

plot( p_grid, pkposterior, 
      type="b",
      xlab="Probability of water",
      ylab="Posterior probability")
points(p_grid, pkprior, col='magenta')
points(p_grid, posterior, col='cyan')
mtext( "Peaked prior, 100 grid points")
```

## Triangular distriution

```{r}
#install.packages(extraDistr)
library(extraDistr)
??extraDistr
x <- rtriang(1e5, 0, 1, 0.1)
hist(x, 100, freq = FALSE)
#curve(dtriang(x, 5, 7, 6), 3, 10, n = 500, col = "red", add = TRUE)
#hist(ptriang(x, 5, 7, 6))
#plot(ecdf(x))
#curve(ptriang(x, 5, 7, 6), 3, 10, n = 500, col = "red", lwd = 2, add = TRUE)
```

## Repeat with triangle prior

```{r}
tprior  <- dtriang(p_grid, 0, 1, 0.1)/sum(dtriang(p_grid, 0, 1, 0.1))
sum(tprior)

plot( p_grid, tprior, 
      type="b",
      xlab="Probability of water",
      ylab="Prior probability")
```

```{r}
likelihood <-dbinom(6,size=9,prob=p_grid)
unstd.tposterior <-likelihood*tprior
tposterior <-unstd.tposterior/sum(unstd.tposterior)
tposterior
plot( p_grid, tposterior, 
      type="b",
      xlab="Probability of water",
      ylab="Prior probability")
points(p_grid, tprior, col='magenta')
points(p_grid, tposterior, col='cyan')
```


